### ISSUE TITLE
When compiling the ssr project, an error is reported, and the client is ok

### ISSUE THREAD

**Issue by lyxverycool** [Chris927/react-roughviz#11] opened 2019-12-27 03:08 UTC

**Comment by Chris927** [comment] 2019-12-27 10:37
Hi @lyxverycool Thanks for reporting this.

Please provide an example project or repository that demonstrates the issue.

**Comment by Chris927** [comment] 2020-02-03 06:31
Hi @lyxverycool 

As I am unable to reproduce the issue with an example, I am closing this issue.

Feel free to re-open, once you can provide an example.

**Closed by Chris927** 2020-02-03 06:31 UTC
